import {
    FaRobot,
    FaImage,
    FaUserMd,
    FaHardHat,
    FaLaptopCode,
    FaChalkboardTeacher,
    FaBriefcase,
    FaBook,
    FaMusic,
    FaCamera,
    FaChartLine,
} from 'react-icons/fa';
import { SiOpenai } from 'react-icons/si';

export const AIPersonas = [
    // {
    //     key: 'BABAGPT',
    //     name: 'BabaGPT',
    //     role: "BABAGPT",
    //     icon: FaHardHat,
    //     color: 'from-blue-400 to-purple-500',
    //     engine: 'BabaGPT',
    //     provider: 'perplexity',
    //     modelCodeName: 'pplx-7b-online',
    //     avatar: '/images/personas/babagpt.jpg',
    // },
    {
        key: 'CHATGPT',
        name: 'ChatGPT',
        role: 'CHATGPT',
        icon: SiOpenai,
        color: 'from-green-400 to-blue-500',
        engine: 'openai',
        provider: 'openai',
        modelCodeName: 'o1-mini',
        avatar: '/images/personas/chatgpt.jpg',
    },
    // {
    //     key: 'JINA',
    //     name: 'Jina',
    //     role: 'Doctor',
    //     icon: FaUserMd,
    //     color: 'from-red-400 to-pink-500',
    //     engine: 'BabaGPT',
    //     provider: 'BabaGPT',
    //     modelCodeName: 'gpt-4o-mini-2024-07-18',
    //     avatar: '/images/personas/doctor.jpg',
    // },
    // {
    //     key: 'ALBERTO',
    //     name: 'Emilio',
    //     role: 'Engineer',
    //     icon: FaHardHat,
    //     color: 'from-blue-400 to-indigo-500',
    //     engine: 'BabaGPT',
    //     provider: 'openai',
    //     modelCodeName: 'gpt-4o-mini-2024-07-18',
    //     avatar: '/images/personas/engineer.jpg',
    // },
    // {
    //     key: 'ALEX',
    //     name: 'Alex',
    //     role: 'Business Advisor',
    //     icon: FaBriefcase,
    //     color: 'from-indigo-400 to-purple-500',
    //     engine: 'BabaGPT',
    //     provider: 'openai',
    //     modelCodeName: 'gpt-4o-mini-2024-07-18',
    //     avatar: '/images/personas/business_advisor.jpg',
    // },
    // {
    //     key: 'Nika',
    //     name: 'Nika',
    //     role: 'Data Analyst',
    //     icon: FaChartLine,
    //     color: 'from-green-400 to-blue-500',
    //     engine: 'BabaGPT',
    //     provider: 'openai',
    //     modelCodeName: 'gpt-4o-mini-2024-07-18',
    //     avatar: '/images/personas/data_analyst.jpg',
    // },
    // {
    //     key: 'Sarah',
    //     name: 'Sarah',
    //     role: 'Musician',
    //     icon: FaMusic,
    //     color: 'from-purple-400 to-indigo-500',
    //     engine: 'BabaGPT',
    //     provider: 'BabaGPT',
    //     modelCodeName: 'claude-3-opus-20240229',
    //     avatar: '/images/personas/musician.jpg',
    // },
    // {
    //     key: 'TAXHELPER',
    //     name: 'Alan',
    //     role: 'Tax Helper',
    //     icon: FaRobot,
    //     color: 'from-yellow-400 to-pink-500',
    //     engine: 'BabaGPT',
    //     provider: 'openai',
    //     modelCodeName: 'gpt-4o-mini-2024-07-18',
    //     avatar: '/images/personas/tax_helper.jpg',
    // },
    // {
    //     key: 'Jack',
    //     name: 'Jack',
    //     role: 'Content Writer',
    //     icon: FaBook,
    //     color: 'from-pink-400 to-red-500',
    //     engine: 'BabaGPT',
    //     provider: 'claude',
    //     modelCodeName: 'claude-3-opus-20240229',
    //     avatar: '/images/personas/content_writer.jpg',
    // },
    // {
    //     key: 'KOOROSH',
    //     name: 'Koorosh',
    //     role: 'Developer',
    //     icon: FaLaptopCode,
    //     color: 'from-green-400 to-teal-500',
    //     engine: 'BabaGPT',
    //     provider: 'openai',
    //     modelCodeName: 'gpt-4o-mini-2024-07-18',
    //     avatar: '/images/personas/developer.jpg',
    // },
    // {
    //     key: 'Maryam',
    //     name: 'Maryam',
    //     role: 'Teacher',
    //     icon: FaChalkboardTeacher,
    //     color: 'from-yellow-400 to-red-500',
    //     engine: 'BabaGPT',
    //     provider: 'openai',
    //     modelCodeName: 'gpt-4o-mini-2024-07-18',
    //     avatar: '/images/personas/teacher.jpg',
    // },
    // {
    //     key: 'MIA',
    //     name: 'Nicéphore',
    //     role: 'Photographer',
    //     icon: FaCamera,
    //     color: 'from-yellow-400 to-pink-500',
    //     engine: 'BabaGPT',
    //     provider: 'dalle',
    //     modelCodeName: 'dall-e-3',
    //     avatar: '/images/personas/photographer.jpg',
    // },
];
