import {
    FaRobot,
    FaImage,
    FaUserMd,
    FaHardHat,
    FaLaptopCode,
    FaChalkboardTeacher,
    FaBriefcase,
    FaBook,
    FaMusic,
    FaCamera,
    FaChartLine,
    FaGlobe,
} from 'react-icons/fa';
import { SiOpenai } from 'react-icons/si';

export const AIPersonas = [
    // Uncomment and modify as needed
    // {
    //     key: 'BABAGPT',
    //     name: 'BabaGPT',
    //     role: "BABAGPT",
    //     icon: FaHardHat,
    //     color: 'from-blue-400 to-purple-500',
    //     engine: 'BabaGPT',
    //     provider: 'perplexity',
    //     modelCodeName: 'pplx-7b-online',
    //     avatar: '/images/personas/babagpt.jpg',
    //     description: 'BabaGPT is specialized in providing insights for construction projects...',
    // },


    // OpenAI Models
    {
        key: 'CHATGPT-o1-preview',
        name: 'o1-preview',
        role: 'CHATGPT',
        type: 'text',
        icon: SiOpenai,
        color: 'from-green-400 to-blue-500',
        engine: 'OpenAI',
        provider: 'openai',
        modelCodeName: 'o1-preview',
        capabilities: {
            supportsSystemMessage: false,
            supportedParameters: {
                maxTokens: {
                    name: 'max_completion_tokens',
                    default: 1000,
                },
                temperature: {
                    supported: false,
                    default: 1,
                },
            },
        },
        features: {
            suitableFor: ['Content Creation', 'Academic Research', 'Coding Assistance'],
            bestFor: ['Detailed Explanations', 'Concise Summaries'],
            specificFeatures: ['Language Support', 'Customization'],
        },
        instructions: 'You are an AI assistant for advanced interactions...',
        description:
            'o1-preview is designed for generating comprehensive and detailed responses, suitable for in-depth analysis and extended conversations.',
        avatar: '/images/personas/chatgpt.jpg',
        metadata: {
            apiEndpoint: '/api/chatgpt-o1-preview',
            usageLimit: 5000,
            createdAt: '2024-01-01',
            updatedAt: '2024-06-01',
        },
    },
    {
        key: 'CHATGPT-o1-mini',
        name: 'o1-mini',
        role: 'CHATGPT',
        type: 'text',
        icon: SiOpenai,
        color: 'from-gray-400 to-gray-500',
        engine: 'OpenAI',
        provider: 'openai',
        modelCodeName: 'o1-mini',
        capabilities: {
            supportsSystemMessage: false,
            supportedParameters: {
                maxTokens: {
                    name: 'max_completion_tokens',
                    default: 1000,
                },
                temperature: {
                    supported: false,
                    default: 1,
                },
            },
        },
        features: {
            suitableFor: ['Quick Queries', 'Customer Support'],
            bestFor: ['Concise Summaries', 'Interactive Assistance'],
            specificFeatures: ['Integration Capabilities'],
        },
        instructions: 'You are an advanced AI assistant...',
        description:
            'o1-mini offers quick and efficient responses, ideal for short queries and fast-paced interactions.',
        avatar: '/images/personas/chatgpt.jpg',
        metadata: {
            apiEndpoint: '/api/chatgpt-o1-mini',
            usageLimit: 3000,
            createdAt: '2024-03-10',
            updatedAt: '2024-08-05',
        },
    },
    {
        key: 'CHATGPT-4o',
        name: '4o',
        role: 'CHATGPT',
        type: 'text',
        icon: SiOpenai,
        color: 'from-green-400 to-blue-500',
        engine: 'OpenAI',
        provider: 'openai',
        modelCodeName: 'chatgpt-4o-latest',
        capabilities: {
            supportsSystemMessage: true,
            supportedParameters: {
                maxTokens: {
                    name: 'max_tokens',
                    default: 1000,
                },
                temperature: {
                    supported: true,
                    default: 0.7,
                },
            },
        },
        features: {
            suitableFor: ['Content Creation', 'Academic Research'],
            bestFor: ['Interactive Assistance', 'Concise Summaries'],
            specificFeatures: ['Customization', 'Real-Time Collaboration'],
        },
        instructions: 'You are an analytical assistant...',
        description:
            '4o is an analytical assistant capable of adjusting response creativity and length, perfect for tailored and nuanced conversations.',
        avatar: '/images/personas/chatgpt.jpg',
        metadata: {
            apiEndpoint: '/api/chatgpt-4o',
            usageLimit: 6000,
            createdAt: '2024-04-15',
            updatedAt: '2024-09-10',
        },
    },
    // Claude Models
    {
        key: 'CLAUDE-3',
        name: 'Claude',
        role: 'Analytical Assistant',
        type: 'text',
        icon: FaGlobe, // Globe icon to represent language
        color: 'from-yellow-400 to-orange-500',
        engine: 'Anthropic',
        provider: 'anthropic',
        modelCodeName: 'claude-3',
        capabilities: {
            supportsSystemMessage: true,
            supportedParameters: {
                maxTokens: {
                    name: 'max_tokens',
                    default: 1500,
                },
                temperature: {
                    supported: true,
                    default: 0.6,
                },
            },
        },
        features: {
            suitableFor: ['Data Analysis', 'Academic Research'],
            bestFor: ['Detailed Explanations', 'Data-Driven Decisions'],
            specificFeatures: ['Customization', 'Security Features'],
        },
        instructions:
            'You are an analytical AI assistant, proficient in understanding and generating human-like text based on the provided inputs. Provide clear, concise, and accurate responses to user queries.',
        description:
            'Claude excels in delivering clear and concise analytical insights, making it ideal for data-driven decision-making and detailed explanations.',
        avatar: '/images/personas/claude.webp', // Ensure this image exists in your project
        metadata: {
            apiEndpoint: '/api/claude-3',
            usageLimit: 7000,
            createdAt: '2024-02-15',
            updatedAt: '2024-07-20',
        },
    },
    // {
    //     key: 'Sarah',
    //     name: 'Sarah',
    //     role: 'Musician',
    //     icon: FaMusic,
    //     color: 'from-purple-400 to-indigo-500',
    //     engine: 'BabaGPT',
    //     provider: 'BabaGPT',
    //     modelCodeName: 'claude-3-opus-20240229',
    //     avatar: '/images/personas/musician.jpg',
    // },
    // {
    //     key: 'JINA',
    //     name: 'Jina',
    //     role: 'Doctor',
    //     icon: FaUserMd,
    //     color: 'from-red-400 to-pink-500',
    //     engine: 'BabaGPT',
    //     provider: 'BabaGPT',
    //     modelCodeName: 'gpt-4o-mini-2024-07-18',
    //     avatar: '/images/personas/doctor.jpg',
    // },
    // {
    //     key: 'ALBERTO',
    //     name: 'Emilio',
    //     role: 'Engineer',
    //     icon: FaHardHat,
    //     color: 'from-blue-400 to-indigo-500',
    //     engine: 'BabaGPT',
    //     provider: 'openai',
    //     modelCodeName: 'gpt-4o-mini-2024-07-18',
    //     avatar: '/images/personas/engineer.jpg',
    // },
    // {
    //     key: 'ALEX',
    //     name: 'Alex',
    //     role: 'Business Advisor',
    //     icon: FaBriefcase,
    //     color: 'from-indigo-400 to-purple-500',
    //     engine: 'BabaGPT',
    //     provider: 'openai',
    //     modelCodeName: 'gpt-4o-mini-2024-07-18',
    //     avatar: '/images/personas/business_advisor.jpg',
    // },
    // {
    //     key: 'Nika',
    //     name: 'Nika',
    //     role: 'Data Analyst',
    //     icon: FaChartLine,
    //     color: 'from-green-400 to-blue-500',
    //     engine: 'BabaGPT',
    //     provider: 'openai',
    //     modelCodeName: 'gpt-4o-mini-2024-07-18',
    //     avatar: '/images/personas/data_analyst.jpg',
    // },
    // {
    //     key: 'TAXHELPER',
    //     name: 'Alan',
    //     role: 'Tax Helper',
    //     icon: FaRobot,
    //     color: 'from-yellow-400 to-pink-500',
    //     engine: 'BabaGPT',
    //     provider: 'openai',
    //     modelCodeName: 'gpt-4o-mini-2024-07-18',
    //     avatar: '/images/personas/tax_helper.jpg',
    // },
    // {
    //     key: 'Jack',
    //     name: 'Jack',
    //     role: 'Content Writer',
    //     icon: FaBook,
    //     color: 'from-pink-400 to-red-500',
    //     engine: 'BabaGPT',
    //     provider: 'claude',
    //     modelCodeName: 'claude-3-opus-20240229',
    //     avatar: '/images/personas/content_writer.jpg',
    // },
    // {
    //     key: 'KOOROSH',
    //     name: 'Koorosh',
    //     role: 'Developer',
    //     icon: FaLaptopCode,
    //     color: 'from-green-400 to-teal-500',
    //     engine: 'BabaGPT',
    //     provider: 'openai',
    //     modelCodeName: 'gpt-4o-mini-2024-07-18',
    //     avatar: '/images/personas/developer.jpg',
    // },
    // {
    //     key: 'Maryam',
    //     name: 'Maryam',
    //     role: 'Teacher',
    //     icon: FaChalkboardTeacher,
    //     color: 'from-yellow-400 to-red-500',
    //     engine: 'BabaGPT',
    //     provider: 'openai',
    //     modelCodeName: 'gpt-4o-mini-2024-07-18',
    //     avatar: '/images/personas/teacher.jpg',
    // },
    // {
    //     key: 'MIA',
    //     name: 'Nicéphore',
    //     role: 'Photographer',
    //     icon: FaCamera,
    //     color: 'from-yellow-400 to-pink-500',
    //     engine: 'BabaGPT',
    //     provider: 'dalle',
    //     modelCodeName: 'dall-e-3',
    //     avatar: '/images/personas/photographer.jpg',
    // },
];
